# Generated by Django 4.0.4 on 2022-05-17 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clasificacion',
            options={'verbose_name_plural': 'Clasificaciones'},
        ),
        migrations.AlterModelOptions(
            name='listamaterial',
            options={'verbose_name_plural': 'Lista de materiales'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name_plural': 'Materiales'},
        ),
        migrations.RemoveField(
            model_name='material',
            name='codigo',
        ),
        migrations.AddField(
            model_name='listamaterial',
            name='codigo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.material'),
        ),
    ]
