# Generated by Django 4.0.4 on 2022-05-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_clasificacion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listamaterial',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
