# Generated by Django 4.0.4 on 2022-05-17 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_listamaterial_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listamaterial',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
