# Generated by Django 4.0.4 on 2022-05-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_listamaterial_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='listamaterial',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
