# Generated by Django 4.0.4 on 2022-05-17 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_listamaterial_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listamaterial',
            name='estado',
        ),
        migrations.AddField(
            model_name='listamaterial',
            name='baja',
            field=models.BooleanField(default=False),
        ),
    ]
